"""Added GroupMatch table

Revision ID: 34fec86cdf69
Revises: c327a2384932
Create Date: 2021-03-23 06:21:14.120304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fec86cdf69'
down_revision = 'c327a2384932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_match', sa.Column(
        'started', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_match', 'started')
    # ### end Alembic commands ###
